#break snapmirror

---
- hosts: localhost
  name: ONTAP
  gather_facts: false
  collections: 
   - netapp.ontap 

  vars_prompt:
    - name: hostname
      prompt: Enter destination host IP 
      private: false
    - name: username
      prompt: Enter username
      private: false
    - name: password
      prompt: Enter password
      private: true
    - name: dst_svm
      prompt: Enter destination SVM
      private: false
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dst_svm: "{{ dst_svm }}"
      https: true
      validate_certs: false

  tasks:
  - name: wait for svm-dr {{ hostname }} / {{ dst_svm }} to change to SnapMirrored
    na_ontap_command:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dst_svm: "{{ dst_svm }}"
      https: true
      validate_certs: false
      command: ['snapmirror show -destination-path {{ dst_svm }}: -fields state']
      return_dict: true
    register: svm_dr_status
    until: svm_dr_status.msg.stdout.find("Snapmirrored") != -1
    retries: 12
    delay: 30

#  - name: return svm-dr status
#    debug:
#      msg: "{{ svm_dr_status.msg.stdout_lines[2].split()[2] }}"

