---
- hosts: localhost
  name: ONTAP
  gather_facts: false
  collections: 
   - netapp.ontap 

  vars_prompt:
    - name: hostname
      prompt: Enter destination host IP 
      private: false
    - name: username
      prompt: Enter username
      private: false
    - name: password
      prompt: Enter password
      private: true
    - name: svm 
      prompt: Enter SVM name
      private: false
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dst_svm: "{{ svm }}"
      https: true
      validate_certs: false

  tasks:
  - name: Break svm-dr mirror for {{ hostname }} / {{ svm }}
    na_ontap_command:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      svm: "{{ svm }}"
      vol: volume
      https: true
      validate_certs: false
      command: ['snapmirror break -destination-path {{ svm }}:']
      

      
