---
- hosts: localhost
  collections:
    - netapp.ontap
#    - netapp.ontap.na_ontap_volume
  name: Test display cluster information

  vars_prompt:
    - name: hostname
      prompt: Enter host IP
      private: false

    - name: username
      prompt: Enter username
      private: false

    - name: password
      prompt: Enter password 
      private: true
  vars: 
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

  tasks:
  
  - name: Get volume info
    na_ontap_info:
      state: info
      gather_subset: volume_info
      <<: *login
    register: results
  - name: Display results
    debug: 
      msg: "{{ results }}"
