# i guess this could work?

---
- hosts: localhost
  collections: 
    - netapp.ontap
  name: Need me some breakup
  
  vars_prompt:
    - name: uname
      prompt: Enter username
      private: false
    - name: pass
      prompt: Enter pass
      private: true
#    - name: svm
#      prompt: Enter SVM
#      private: false
  vars:
    login: &login
      hostname: 192.168.89.120
      https: true
      validate_certs: false

  tasks:
  - name: i need a volume! or at least it's state!
    na_ontap_command:
      hostname: 192.168.89.120
      username: "{{ uname }}"
      password: "{{ pass }}"
#      dst_svm: "{{ svm }}"
      https: true
      validate_certs: false
      command: ['snapmirror show -destination-path iSCSI_repo:* -fields state']
      return_dict: true
    register: svmdrstatus
    until: svmdrstatus.msg.stdout.find("Snapmirrored") != -1
    retries: 15
    delay: 5
  - name: display that shit!
    debug:
      msg: "{{ svmdrstatus.msg.stdout_lines[2].split()[2] }}"
